################################################################################
#
################################################################################
service: dpnt-video

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'local'}
  region: eu-west-2

  memorySize: 1536 # in MB
  timeout: 120 # in seconds
  versionFunctions: false
  environment: ${file(config/${self:provider.stage}.params.yml)}

  iamRoleStatements:

  # List Videos bucket
  - Effect: "Allow"
    Action:
    - "s3:ListBucket"
    - "s3:ListBucketMultipartUploads"
    Resource:
    - ${self:provider.environment.S3_VIDEO_CLIENT_UPLOAD_BUCKET_ARN}
    - ${self:provider.environment.S3_VIDEO_ACCUMULATOR_BUCKET_ARN}

  # Read Videos bucket
  - Effect: "Allow"
    Action:
    - "s3:GetObject"
    Resource:
      Fn::Join:
      - ""
      - - ${self:provider.environment.S3_VIDEO_CLIENT_UPLOAD_BUCKET_ARN}
        - ${self:provider.environment.S3_VIDEO_ACCUMULATOR_BUCKET_ARN}
        - "/*"

  # Publish events
  - Effect: "Allow"
    Action:
    - "sqs:GetQueueAttributes"
    - "sqs:SendMessageBatch"
    - "sqs:SendMessage"
    Resource:
    - ${self:provider.environment.SQS_QUEUE_ARN}

  # Trigger ECS Task
  - Effect: "Allow"
    Action:
    - "ecs:RunTask"
    Resource:
      Fn::Join:
      - ""
      - - "arn:aws:ecs:"
        - ${self:provider.environment.ECS_REGION}
        - ":"
        - ${self:provider.environment.ECS_ACCOUNT_ID}
        - ":task-definition/"
        - ${self:provider.environment.ECS_TASK_DEFINITION_PREFIX}
        - "*"
  - Effect: "Allow"
    Action:
    - "iam:PassRole"
    Resource:
    - "arn:aws:iam::577770582757:role/ecsTaskExecutionRole"
    - Fn::Join:
      - ""
      - - "arn:aws:iam::577770582757:role/"
        - ${self:provider.environment.ECS_TASK_CLUSTER}
        - "-taskRole"

package:
  artifact: build/libs/dpnt-video-all.jar

functions:
  call-ecs-to-merge-video:
    handler: tdl.datapoint.video.VideoUploadHandler
    onError: arn:aws:sns:eu-west-2:577770582757:MyselfEU2
