package tdl.datapoint.video;

public enum ApplicationEnv {
    S3_ENDPOINT,
    S3_REGION,
    S3_VIDEO_URL_TOKEN_SECRET,

    ECS_ENDPOINT,
    ECS_REGION,
    ECS_TASK_CLUSTER,
    ECS_TASK_DEFINITION_PREFIX,
    ECS_TASK_LAUNCH_TYPE,
    ECS_VPC_SUBNET,
    ECS_VPC_SECURITY_GROUP,
    ECS_VPC_ASSIGN_PUBLIC_IP,

    SQS_ENDPOINT,
    SQS_REGION,
    SQS_QUEUE_URL,
}
